### ISSUE TITLE
attempt to index a nil value (field 'set_variables')

### ISSUE THREAD

**Issue by Thekuca** [lunarmodules/luacheck#93] opened 2023-05-04 21:22 UTC
![Screenshot_1798](https://user-images.githubusercontent.com/63980591/236332952-2550a5a0-16f3-46e0-814e-822b2ea8aa10.png)

**Comment by alerque** [comment] 2023-05-04 22:25
What platform are you on? And do you have a MWE of input code that triggers this when linted?

**Comment by Thekuca** [comment] 2023-05-05 10:54
> What platform are you on? And do you have a MWE of input code that triggers this when linted?

![Screenshot_1799](https://user-images.githubusercontent.com/63980591/236439815-2434670e-955c-43a6-b8ac-352a08582608.png)

**Comment by Thekuca** [comment] 2023-05-05 10:54
running through https://github.com/iLLeniumStudios/fivem-lua-lint-action

**Comment by arichard4** [comment] 2023-05-06 05:09
That doesn't let us repro, since we can't see what specifically it's testing against; that said, pretty sure the issue is with the recent compound operator addition. It added a new operator, OpSet, but LinState:register_set_variables checks against "Local" and "Set" tags in setting set_variables, so OpSet might get missed. If you have a repro, can you make that modification and see if it's fixed?

In fact, I think that everywhere that checked against "Set" should also check against "OpSet", unless I'm confused?

**Comment by Thekuca** [comment] 2023-05-06 19:28
any code i lint it does the same

**Comment by alerque** [comment] 2023-05-06 19:33
If *any* code you lint does the same then the bug you need to hunt is going to be in the action you are using to run it not `luacheck` itself.

**Comment by TheBanHammer** [comment] 2023-05-07 14:52
I've got a similar issue appearing for FiveM code however I run this on a self-hosted GitLab build agent.

I've tested this against multiple sources of code however only receive the error described above when the `+=` operator is in use. If I replace the instances with the long form code it'll validate fine.

Below shows an example of what needed to be changed in order for luacheck to run without errors.

![image](https://user-images.githubusercontent.com/6783447/236684529-f0569cb3-8f7f-4da2-9c9a-a3aa0e6e3e35.png)

Let me know if you need anything else to test it with.

**Comment by TheFantomas** [comment] 2023-05-07 17:30
Hello,

Thank you so much for your help with this problem. I'm very glad for the help and solving this problem.

I am writing on behalf of Developer TheKuca as he is one of our members.

Sincerely and respectfully
ESX Legacy Management
Fantík

**Comment by arichard4** [comment] 2023-06-05 15:42
Found a minimal repro case:

```
local x = 5
function mod()
	x += 6
end
mod()
print(x)
```

As I thought, the issue is indeed around the recent OpSet change missing some places that had been checking against "Set" and now also needed to check against "OpSet". Unfortunately there's multiple places this switch might need to be made, I'll look into them.

Folks reporting, is there an example of a public codebase that I can run these checks on?

**Comment by arichard4** [comment] 2023-06-05 17:59
If anybody repro'ing is able to test, can you see if PR #96 fixes the issue? I am still not sure if I have found *your* issue, i.e. if my repro case above is the same as the cause of the reported issue.

**Comment by arichard4** [comment] 2023-06-11 08:00
Maybe fixed in 1.1.1? Can people still repro this with the new release?

**Comment by alerque** [comment] 2023-06-12 13:28
I think we'll go with "fixed unless proven otherwise", mostly because some participants may not be notified unless we ming specifically or the status changes.

Hence status: closed — but please anybody do feel to jump in with a comment if this is still a problem for you in any way and we're happy to reevaluate.

**Closed by alerque** 2023-06-12 13:28 UTC
